### ISSUE TITLE
cloudnative-pg container nil pointer

### ISSUE THREAD

**Issue by rwlove** [cloudnative-pg/cloudnative-pg#1574]
I am not sure what happened to my cluster to cause this, but I'm now hitting this failure when I start CNPG. 

```
➜  fleet-infra git:(main) ✗ kubectl -n databases logs cloudnative-pg-844894c959-s2clk -f
<snip>
{"level":"info","ts":"2023-02-24T19:51:34Z","msg":"Starting Controller","controller":"pooler","controllerGroup":"postgresql.cnpg.io","controllerKind":"Pooler"}
{"level":"info","ts":"2023-02-24T19:51:34Z","msg":"Starting workers","controller":"backup","controllerGroup":"postgresql.cnpg.io","controllerKind":"Backup","worker count":1}
{"level":"info","ts":"2023-02-24T19:51:35Z","msg":"Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference","controller":"backup","controllerGroup":"postgresql.cnpg.io","controllerKind":"Backup","Backup":{"name":"postgres-1677266787","namespace":"databases"},"namespace":"databases","name":"postgres-1677266787","reconcileID":"c02d17d8-846d-4dd3-a4d2-22d4023b3333"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1948f4e]

goroutine 730 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:119 +0x1fa
panic({0x1bd9b60, 0x304bc90})
	/opt/hostedtoolcache/go/1.19.5/x64/src/runtime/panic.go:884 +0x212
github.com/cloudnative-pg/cloudnative-pg/controllers.(*BackupReconciler).getBackupTargetPod(_, {_, _}, {{{0x19cfa25, 0x7}, {0xc0005ba2a0, 0x15}}, {{0xc0000380c0, 0x8}, {0x0, ...}, ...}, ...})
	controllers/backup_controller.go:213 +0x2ee
github.com/cloudnative-pg/cloudnative-pg/controllers.(*BackupReconciler).Reconcile(0xc000abdd10, {0x2195718?, 0xc00138a720?}, {{{0xc000b243f0, 0x9}, {0xc00002c2e8, 0x13}}})
	controllers/backup_controller.go:126 +0x8e6
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x2195718?, {0x2195718?, 0xc00138a720?}, {{{0xc000b243f0?, 0x1af11e0?}, {0xc00002c2e8?, 0x0?}}})
	pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:122 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00002e280, {0x2195670, 0xc0003fe3c0}, {0x1c73780?, 0xc000bd2720?})
	pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:323 +0x38f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00002e280, {0x2195670, 0xc0003fe3c0})
	pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:274 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:235 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:231 +0x333
```

I believe that this results in:
```
Every 2.0s: flux get kustomizations -A                                                                                                         rover: Fri Feb 24 15:03:01 2023

NAMESPACE	NAME                            REVISION                                                                        SUSPENDED	READY   MESSAGE


flux-system     apps                            main@sha1:fa316ec54e7626227068b4f1aadb54c7eeb42a45                              False           False   Cluster/databases/post
gres dry-run failed, reason: InternalError, error: Internal error occurred: failed calling webhook "mcluster.kb.io": failed to call webhook: Post "https://cnpg-webhook-servic
e.databases.svc:443/mutate-postgresql-cnpg-io-v1-cluster?timeout=10s": dial tcp 11.105.165.169:443: connect: operation not permitted
```

**Comment by phisco** [comment]
Hi @rwlove, can you provide the manifest of the backup `{"name":"postgres-1677266787","namespace":"databases"}` and the Cluster it points to please?
I think it was already solved on `main` with #1533.
A quick fix for you in the meantime, waiting for the  next patch release, would be to just delete the Backup, as most probably it's pointing to a Cluster that does not have a `backup` configured.

**Comment by rwlove** [comment]
I think you're on to something. I don't think I have a backup configured correctly. I rolled back to 1.16.1 and I'm up and running again.

I'll try to configure the backend and upgrade again.

**Comment by rwlove** [comment]
I've configured the backup and I don't hit this problem anymore.

**Comment by meltingrock** [comment]
I had the same issue, BUT the mistake as on my side and I am posting this for the next one that makes a similar mistake. 

The error was due to me not adding Google bucket backup creds to the cluster config. Maybe this omission could be handled instead of having the operator fail.
