### ISSUE TITLE
[Bug]: `panic: runtime error:` when compiling the source code

### ISSUE THREAD

**Issue by gbartolini** [cloudnative-pg/cloudnative-pg#3876]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

trunk (main)

### What version of Kubernetes are you using?

1.28

### What is your Kubernetes environment?

Self-managed: kind (evaluation)

### How did you install the operator?

YAML manifest

### What happened?

I ran `make` and got this:

```
GOBIN=/Users/gabriele.bartolini/prj/cloudnative-pg/cloudnative-pg/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.13.0
/Users/gabriele.bartolini/prj/cloudnative-pg/cloudnative-pg/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3e509fe]

goroutine 69 [running]:
go/types.(*Checker).handleBailout(0xc0004f3a00, 0xc00144dd40)
	/usr/local/Cellar/go/1.22.0/libexec/src/go/types/check.go:367 +0x88
panic({0x4149c40?, 0x4701a70?})
	/usr/local/Cellar/go/1.22.0/libexec/src/runtime/panic.go:770 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0x4214c30, 0x470a200})
	/usr/local/Cellar/go/1.22.0/libexec/src/go/types/sizes.go:228 +0x31e
go/types.(*Config).sizeof(...)
	/usr/local/Cellar/go/1.22.0/libexec/src/go/types/sizes.go:333
go/types.representableConst.func1({0x4214c30?, 0x470a200?})
	/usr/local/Cellar/go/1.22.0/libexec/src/go/types/const.go:76 +0x9e
go/types.representableConst({0x421aed0, 0x46d51c8}, 0xc0004f3a00, 0x470a200, 0xc00144cb98)
	/usr/local/Cellar/go/1.22.0/libexec/src/go/types/const.go:92 +0x192
go/types.(*Checker).representation(0xc0004f3a00, 0xc001451900, 0x470a200)
	/usr/local/Cellar/go/1.22.0/libexec/src/go/types/const.go:256 +0x65
go/types.(*Checker).implicitTypeAndValue(0xc0004f3a00, 0xc001451900, {0x4214c30, 0x470a200})
	/usr/local/Cellar/go/1.22.0/libexec/src/go/types/expr.go:375 +0x30d
go/types.(*Checker).assignment(0xc0004f3a00, 0xc001451900, {0x4214c30, 0x470a200}, {0x3f8306c, 0xe})
	/usr/local/Cellar/go/1.22.0/libexec/src/go/types/assignments.go:52 +0x2e5
go/types.(*Checker).exprInternal(0xc0004f3a00, 0x0, 0xc001451900, {0x4218c78, 0xc0003da080}, {0x0, 0x0})
	/usr/local/Cellar/go/1.22.0/libexec/src/go/types/expr.go:1175 +0x26dc
go/types.(*Checker).rawExpr(0xc0004f3a00, 0x0, 0xc001451900, {0x4218c78?, 0xc0003da080?}, {0x0?, 0x0?}, 0x0)
	/usr/local/Cellar/go/1.22.0/libexec/src/go/types/expr.go:979 +0x19e
go/types.(*Checker).expr(0xc0004f3a00, 0x0?, 0xc001451900, {0x4218c78?, 0xc0003da080?})
	/usr/local/Cellar/go/1.22.0/libexec/src/go/types/expr.go:1513 +0x30
go/types.(*Checker).varDecl(0xc0004f3a00, 0xc000321c20, {0xc000520b38, 0x1, 0x1}, {0x0, 0x0}, {0x4218c78, 0xc0003da080})
	/usr/local/Cellar/go/1.22.0/libexec/src/go/types/decl.go:521 +0x17b
go/types.(*Checker).objDecl(0xc0004f3a00, {0x4220058, 0xc000321c20}, 0x0)
	/usr/local/Cellar/go/1.22.0/libexec/src/go/types/decl.go:194 +0x9e5
go/types.(*Checker).packageObjects(0xc0004f3a00)
	/usr/local/Cellar/go/1.22.0/libexec/src/go/types/resolver.go:693 +0x4dd
go/types.(*Checker).checkFiles(0xc0004f3a00, {0xc000954610, 0x2, 0x2})
	/usr/local/Cellar/go/1.22.0/libexec/src/go/types/check.go:408 +0x1a5
go/types.(*Checker).Files(...)
	/usr/local/Cellar/go/1.22.0/libexec/src/go/types/check.go:372
sigs.k8s.io/controller-tools/pkg/loader.(*loader).typeCheck(0xc0002fb3b0, 0xc001035860)
	/Users/gabriele.bartolini/go/pkg/mod/sigs.k8s.io/controller-tools@v0.13.0/pkg/loader/loader.go:286 +0x36a
sigs.k8s.io/controller-tools/pkg/loader.(*Package).NeedTypesInfo(0xc001035860)
	/Users/gabriele.bartolini/go/pkg/mod/sigs.k8s.io/controller-tools@v0.13.0/pkg/loader/loader.go:99 +0x39
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0xc001410ea0, 0xc001035860)
	/Users/gabriele.bartolini/go/pkg/mod/sigs.k8s.io/controller-tools@v0.13.0/pkg/loader/refs.go:268 +0x2b7
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check.func1(0x0?)
	/Users/gabriele.bartolini/go/pkg/mod/sigs.k8s.io/controller-tools@v0.13.0/pkg/loader/refs.go:262 +0x53
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check in goroutine 1
	/Users/gabriele.bartolini/go/pkg/mod/sigs.k8s.io/controller-tools@v0.13.0/pkg/loader/refs.go:260 +0x1c5
make: *** [Makefile:207: generate] Error 2
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sxd** [comment]
This bug will be fixed with the following PRs
https://github.com/cloudnative-pg/cloudnative-pg/pull/3877
https://github.com/cloudnative-pg/cloudnative-pg/pull/3878
https://github.com/cloudnative-pg/cloudnative-pg/pull/3879

**Comment by sxd** [comment]
PRs are merged this should be fixed by now

**Comment by gbartolini** [comment]
I confirm I just had to run `make distclean` then `make` and it all worked. Thanks.
